# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: husk
version: '0.0.1'
license: MIT
maintainer: Providence Salumu
synopsis: A new Haskeleton package.
category: Other
github: smunix/husk
description: husk is a new Haskeleton package.

flags:
  documentation:
    description : "Generate documentation"
    manual : true
    default : false
  fast:
    description : "Build optimized executable (husk)"
    manual : true
    default : true

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall

benchmarks:
  husk-benchmarks:
    dependencies:
    - base
    - husk
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark

executables:
  husk:
    dependencies:
    - base
    - husk
    when:
      - condition: flag(fast)
        then:
          ghc-options:
            - -O2
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
        else:
          ghc-options:
            - -O0
            - -Wall
    main: Main.hs
    source-dirs: executable

library:
  when:
    - condition : flag(documentation)
      then:
        dependencies:
          - base
          - hscolour
      else:
        dependencies:
          - base
  source-dirs: library
  exposed-modules: Husk

tests:
  husk-test-suite:
    dependencies:
    - base
    - husk
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

  hpc-test-suite:
    dependencies:
    - base
    - husk
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
    ghc-options:
    - -fhpc
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs:
    - test-suite
    - library
    other-modules: Husk
